parameters:
#    ornj_markdown.example.class: Ornj\Bundle\MarkdownBundle\Example

services:
    ornj_markdown.form.type.markdown:
        class: Ornj\Bundle\MarkdownBundle\Form\Type\MarkdownType
        tags:
            - { name: form.type, alias: markdown }